### ISSUE TITLE
Hi, author

### ISSUE THREAD

**Issue by wuguangbin1230** [tnikolla/robot-grasp-detection#1]
Excuse me,

What is the meaning "in filename[:49] adapt the number 49 (you can contribute, or I will program it better someday)"?

**Comment by tnikolla** [comment]
I edited the code. Now it will run on every system, just make sure to change the path of your dataset in the begining. 

For every image path, for example 

    filename = /root/dataset/grasp_dataset/02/pcd0200r.png

the bounding boxes lie in

    `/root/dataset/grasp_dataset/02/pcd0200cpos.txt`

So I used the image path to lazily create a variable that stores the path of the bounding boxes. This was done by slicing `filename`
    
    # in this example, filename[:38] := /root/dataset/grasp_dataset/02/pcd0200
    bbox = filename[:38] + cpos.txt

This is how the corresponding bounding boxes file is accessed.

**Comment by wuguangbin1230** [comment]
I get it!

Thank you very much!

发自我的 iPhone

在 2017年11月4日，上午1:19，Tomi Nikolla <notifications@github.com<mailto:notifications@github.com>> 写道：


I edited the code. Now it will run on every system, just make sure to change the path of your dataset in the begining.

For every image path, for example

filename = /root/dataset/grasp_dataset/02/pcd0200r.png


the bounding boxes lie in

`/root/dataset/grasp_dataset/02/pcd0200cpos.txt`


So I used the image path to lazily create a variable that stores the path of the bounding boxes. This was done by slicing filename

# in this example, filename[:38] := /root/dataset/grasp_dataset/02/pcd0200
bbox = filename[:38] + cpos.txt


This is how the corresponding bounding boxes file is accessed.

**Comment by wuguangbin1230** [comment]
@tnikolla Thank you for your reply!

Can you give your pre_trained model (.ckpt)?

Thank you!

**Comment by wuguangbin1230** [comment]
@tnikolla Thank you for your reply!

Can you give your pre_trained model (.ckpt)?
My email is wuguangbin1230@outlook.com
Thank you!

**Comment by tnikolla** [comment]
I will upload it in the weekend; the grasp model too.
