### ISSUE TITLE
about pretraining on imagenet

### ISSUE THREAD

**Issue by ClaireTun** [tnikolla/robot-grasp-detection#3]
There are some limits for me to pretrain on imagenet. Can I get the pretrained model? Many thanks!

**Comment by tnikolla** [comment]
Now they are online. Regards!

**Comment by ClaireTun** [comment]
Thank you ！！！！

**Comment by lijialei666** [comment]
Why we should pretrain imagenet,I thank you was not use the pretrain model when I run the grasp_det.py.

**Comment by lijialei666** [comment]
> Why we should pretrain imagenet,I thank you was not use the pretrain model when I run the grasp_det.py.

o,I find you have annotated it.
